- src/scalar.jl
- test/runtests.jl
* Need more tests
* Handle p as vector
> [WIP] AD in Bisection

- src/scalar.jl
- src/utils.jl
@ChrisRackauckas Minor bug fix caught in ode_event_tests.jl. We should get direction tests for this package too.
> Fix direction bug in Falsi

- Project.toml
- src/NonlinearSolve.jl
Because otherwise the default linsolve won't work
> add missing imports

- .github/workflows/Documentation.yml
Not sure that was what was missing but I thought I'd suggest it.
> Deploy docs on release

- src/bisection.jl
- src/falsi.jl
> Fix string concatenation error

- docs/src/basics/NonlinearProblem.md
> Fix docs typo

- src/trustRegion.jl
> Dead links trust region fix

- src/ad.jl
Did you miss this in #232? Gives a warning during precompilation.
> Remove unused iip type parameter

- docs/src/tutorials/advanced.md
Small tweak `@benchmark` -> `@btime`, rest of the example uses `@btime`
> docs: update advanced.md

- src/default.jl
- test/polyalgs.jl
Fixes https://github.com/SciML/NonlinearSolve.jl/issues/153
> Change default in-place specialization

- src/pseudotransient.jl
I think this should fix the first task in #255.
> Finished docs for PseudoTransient

- CITATION.cff
- README.md
Fixes https://github.com/SciML/NonlinearSolve.jl/issues/227 for the time being
The author list is definitely not complete.
> Temporary Citation via Zenodo

- test/23_test_problems.jl
With the true jacobian Klement updates anyways don't work well
> Remove the true jacobian Klement from the tests

- .github/workflows/Downstream.yml
- Project.toml
- src/core/generic.jl
- src/default.jl
Needed for https://github.com/SciML/DiffEqCallbacks.jl/pull/205
> Patches for DiffEqCallbacks

- Project.toml
- src/internal/helpers.jl
- test/downstream/mtk_cache_indexing_tests.jl
- test/misc/other_tests.jl
> Don't warn if user specified FiniteDifferencing

- .github/workflows/CI_BracketingNonlinearSolve.yml
- .github/workflows/CI_NonlinearSolve.yml
- .github/workflows/CI_NonlinearSolveBase.yml
- .github/workflows/CI_NonlinearSolveFirstOrder.yml
- .github/workflows/CI_NonlinearSolveQuasiNewton.yml
- .github/workflows/CI_NonlinearSolveSpectralMethods.yml
- .github/workflows/CI_SciMLJacobianOperators.yml
- .github/workflows/CI_SimpleNonlinearSolve.yml
- .github/workflows/Documentation.yml
- .github/workflows/Downstream.yml
- lib/NonlinearSolveBase/src/abstract_types.jl
- lib/NonlinearSolveBase/src/polyalg.jl
- test/mtk_cache_indexing_tests.jl
> fix: fix SII implementation for caches, tests

- lib/NonlinearSolveBase/src/solve.jl
- test/mtk_cache_indexing_tests.jl
> fix: fix SII implementation for `NonlinearSolveNoInitCache`

- test/mtk_cache_indexing_tests.jl
- test/runtests.jl
> fix: fix MTK indexing tests

- lib/NonlinearSolveBase/ext/NonlinearSolveBaseLinearSolveExt.jl
- lib/NonlinearSolveBase/src/NonlinearSolveBase.jl
- lib/NonlinearSolveBase/src/linear_solve.jl
> Use aliasing API for linear solves

- docs/src/basics/faq.md
> Fix markdown list in faq.md

- lib/BracketingNonlinearSolve/src/itp.jl
This will be a very minor improvement, but it saves a floating point pow, and log and also likely fixes type stability for non Float64 problems)
> minor itp speedups

- lib/NonlinearSolveBase/src/common_defaults.jl
Fixes https://github.com/SciML/NonlinearSolve.jl/issues/524
> Fix generic fallbacks for L2Norm
