- Project.toml
- src/NonlinearSolve.jl
- src/scalar.jl
- src/solve.jl
- src/types.jl
- src/utils.jl
> Remove DiffEqBase Dependency

- Project.toml
- src/NonlinearSolve.jl
- src/scalar.jl
- src/types.jl
- src/utils.jl
- test/runtests.jl
This PR adds forward mode AD overloads for scalar nonlinear equation solvers, i.e. `NewtonRaphson`, `Falsi`, and `Bisection`.
> Scalar nonlinear solve AD

- src/jacobian.jl
- test/runtests.jl
> Fix Newton with finite diff

- Project.toml
If tests pass, there should be a new release of NonlinearSolve.jl since it holds back updates for DiffEqBase.jl (https://github.com/SciML/DiffEqBase.jl/pull/604) which in turns holds back updates for a lot of downstream packages.
This needs a new version of RecursiveArrayTools.jl (https://github.com/SciML/RecursiveArrayTools.jl/pull/123).
> bump compat version bounds

- Project.toml
- src/scalar.jl
- test/runtests.jl
@ChrisRackauckas this one is without special AD fixes, only new Scalar Falsi that works
> Scalar Falsi

- src/scalar.jl
There was an issue where when using NewtonRaphson algorithm with scalars, where `autodiff=false` was ignored.
> updated to account for autodiff=false

- src/utils.jl
Is there a reason why they were so tight?
> loosen types on prev/next floating handling

- src/scalar.jl
- src/solve.jl
- src/types.jl
- src/utils.jl
- test/runtests.jl
Hi,
I have currently added `build_solution` in solve.jl for NewtonRaphson. I did understand what was the purpose of `scalar.jl`. Do I need to add `build_solution` there too? And how to handle bracketing methods for `build_solution`?
@ChrisRackauckas, please have a look.
> Add SciML.build_solution

- src/solve.jl
Required to hit the higher level handling https://github.com/SciML/DiffEqBase.jl/blob/master/src/solve.jl#L745 (and ultimately hit the adjoint dispatches in SciMLSensitivity).
> change `solve` to lower level interface `__solve`

- src/bisection.jl
- src/falsi.jl
- src/scalar.jl
- src/solve.jl
- src/types.jl
- test/basictests.jl
Provides compatibility to execute solves on GPU.
> Change NonlinearSolve enums to SciMLBase enums

- Project.toml
- src/NonlinearSolve.jl
- src/ad.jl
- src/raphson.jl
- src/utils.jl
- test/basictests.jl
Retcode conformity
More tests
Decrease dependencies
SnoopPrecompile
> more general fixes

- Project.toml
- src/raphson.jl
This will save a small amount of work.
> use undefmatrix to init jacobian

- Project.toml
- docs/src/solvers/NonlinearSystemSolvers.md
- src/NonlinearSolve.jl
- src/jacobian.jl
- src/raphson.jl
- src/utils.jl
- test/runtests.jl
- test/sparse.jl
Fixed https://github.com/SciML/NonlinearSolve.jl/issues/53
> Setup with SparseDiffTools

- docs/src/api/simplenonlinearsolve.md
- docs/src/solvers/NonlinearSystemSolvers.md
Adding the new methods from @CCsimon123 to the docs
> Add new SimpleNonlinearSolve methods to the docs

- .gitignore
- src/trustRegion.jl
- test/basictests.jl
This is an attempt to fix the bug that currently exists in the `TrustRegion` solver when `iip=true` #124.
The bug went trough testing because the tests did not take the absolute value, allowing all negative values to pass, i.e. `@test all(sol.u .* sol.u .- 2 .< 1e-9)` and not `@test all(abs.(sol.u .* sol.u .- 2) .< 1e-9)` as it should be.
The bug is due to that `cache.u` and `cache.fu` points to the same vector as `cache.u_tmp` and `cache.fu_new` respectively, and then both of them get changed at unwanted places.
> Bug fix for TrustRegion when iip=true.

- src/NonlinearSolve.jl
Fixes https://github.com/SciML/NonlinearSolve.jl/issues/121
> Precompile trust region only on v1.7+

- src/raphson.jl
- src/trustRegion.jl
- src/utils.jl
When https://github.com/domluna/JuliaFormatter.jl/blob/d89ab9e2638b9273b9d25321cbed5c9f22719e6d/src/styles/sciml/pretty.jl#L41 is changed to true.
I'll go through the repos and format the docstrings,
if that works for all the repos we can change it in the style?
> format docstrings

- src/NonlinearSolve.jl
- src/ad.jl
- src/levenberg.jl
- src/trustRegion.jl
- test/basictests.jl
Implementation of a Levenberg–Marquardt algorithm #119, according to the paper [Improvements to the Levenberg-Marquardt algorithm for nonlinear least-squares minimization](https://arxiv.org/abs/1201.5885).
The solver in `raphson.jl` was used as a template for this solver.
> Implementation of a Levenberg–Marquardt algorithm

- test/23_test_cases.jl
Implementation of the 23 test cases in https://people.sc.fsu.edu/~jburkardt/m_src/test_nonlin/test_nonlin.html according to #142.
The result of the program looks like this:
```
nr  Problem                                            n     NewtonRaphson       TrustRegion         LevenbergMarquardt  nlsolve
1   Generalized Rosenbrock function                    10    2.5809e-8           4.9193              4.9193              0.0
2   Powell singular function                           4     7.0435e-16          7.941               0.021633            7.0217e-16
3   Powell badly scaled function                       2     0.0                 26897.0             2.1983e-14          0.0
4   Wood function                                      4     4.1832e-14          19081.0             8550.5 …
```
> Implementation of 23 test cases

- src/raphson.jl
- test/basictests.jl
The `reinit!` interface for the nonlinear solvers is missing, meaning that the iterator interface cannot be used. I have added the `reinit!` function for the `NewtonRaphsonCache` which re-evaluates the nonlinear function and resets iteration counters. Simple tests are included.
> Added reinit! for NewtonRaphson

- src/raphson.jl
- src/trustRegion.jl
- test/basictests.jl
Similar to #173, this adds the `reinit!` interface for the `TrustRegion` algorithm, along with associated tests.
I've been through the trust region code quite carefully and pulled out all the variables that need reinitialising.
I also fixed a typo in the default arguments of `reinit!` for `NewtonRaphsonCache`.
> Enable iterator interface to be used with TrustRegion

- src/trustRegion.jl
- test/basictests.jl
- test/convergencetests.jl
The last pr got messed up a little so opening a new one. tests pass, formatted with no conflicts!
> Bastin's radius update scheme

- docs/src/tutorials/nonlinear.md
changed the tutorial method to itp [#209]
> Tutorial change for Bracketing method

- src/trustRegion.jl
- test/basictests.jl
I had a look at https://github.com/SciML/NonlinearSolve.jl/issues/142. Indeed there were some mistakes in how the Gauss-Newton step and Cauchy point were calculated. This is still WIP, however, since TrustRegion is still not up to par with nlsolve's implementation after these changes. 
I suspect a large issue for the poor performance is the default TR adaptation and step acceptance/rejection routine; for instance the current default is rather conservative with respect to which steps are being accepted. Lowering the `step_threshold` default to 1e-4 from 0.1 (and after correcting the GN/Cauchy step computations) the performance on the test set is already quite a bit better.
Before
```
nr  Problem                                            n     NewtonRaphson       TrustRegion …
```
> TrustRegion bugs

- Project.toml
- src/NonlinearSolve.jl
- src/jacobian.jl
- src/levenberg.jl
- test/23_test_problems.jl
- test/runtests.jl
> Fix Jacobian Construction for concrete_jac

- .github/workflows/CI.yml
- Project.toml
- src/levenberg.jl
- test/23_test_problems.jl
- test/runtests.jl
```julia
nr  Problem                                            n     NewtonRaphson       TrustRegion         LevenbergMarquardt  LevenberdMarquardt (LSOptim)
1   Generalized Rosenbrock function                    10    NaN                 0.0                 1.0214e-14          5.8944e-11          
2   Powell singular function                           4     7.0435e-16          6.8342e-16          1.0538e-15          2.3573e-7           
3   Powell badly scaled function                       2     0.0                 0.0                 8.7431e-5           2.5957e-11          
4   Wood function                                      4     1.8586e-14          1.0663e-14          1.2104e-14          3.8075e-12          
5   Helical valley function                            3     6.2775e-30 …
```
> Fix bug in Levenberg

- docs/Project.toml
- docs/src/tutorials/advanced.md
> Add docs of AutoSparseForwardDiff and matrix coloring

- Project.toml
- src/ad.jl
These methods are only tested for out-of-place functions right now, and the tests in OrdinaryDiffEq are seeing that they fail on in-place functions. So this changes the dispatches so they only apply when they are known to work. The in-place versions should be added in the future.
> Only apply AD overloads to out-of-place

- Project.toml
- ext/NonlinearSolveFastLevenbergMarquardtExt.jl
- ext/NonlinearSolveLeastSquaresOptimExt.jl
- src/NonlinearSolve.jl
- src/extension_algs.jl
- test/nonlinear_least_squares.jl
Not exactly a non-breaking change, but I renamed the wrapped solvers to conform to the other SciML wrappers
> Rename wrappers to be consistent with other SciML packages

- docs/src/solvers/NonlinearSystemSolvers.md
- src/NonlinearSolve.jl
- src/default.jl
- test/polyalgs.jl
- test/runtests.jl
This adds two polyalgorithms, one focused on ultra-robustness and another focused on mixing robustness and performance, and sets the default algorithm to the balanced one. There's still a lot of improvements that can be done to this, but I think this is good enough to at least have a lot of utility, and the defaults can probably specialize on StaticArrays and stuff like that to further be optimized, but that's fine.
> Add polyalgorithms and a default method

- test/basictests.jl
Fixes https://github.com/SciML/NonlinearSolve.jl/issues/243
> Fix test to use TrustRegion

- src/NonlinearSolve.jl
- src/jacobian.jl
- src/pseudotransient.jl
- test/basictests.jl
This PR adds pseudo-transient  methods using adaptive step size described [here](https://ctk.math.ncsu.edu/PAPERS/Kelley_Liao_2013.pdf) created this new PR since #228 had too many merge conflicts when rebasing
> Pseudo-Transient Method

- src/NonlinearSolve.jl
- test/runtests.jl
* Use `@recompile_invalidations`
> Scary Load Times in 1.9

- Project.toml
- src/NonlinearSolve.jl
- src/levenberg.jl
- test/23_test_problems.jl
- test/basictests.jl
> Fix LM for banded jacobian

- Project.toml
- src/NonlinearSolve.jl
- src/default.jl
- test/polyalgs.jl
Adding this since it makes it easy to write type-stable polyalgorithms. Once this is in we can simply define a custom polyalgorithm algorithm for https://github.com/SciML/NonlinearSolve.jl/pull/277 as well.
> Use a proper polyalgorithm algorithm type

- test/23_test_problems.jl
I forgot to add PT to 23 test problems. This PR fixes that issue
> test PT on 23 test problems

- .github/workflows/SpellCheck.yml
- .typos.toml
- docs/src/solvers/NonlinearSystemSolvers.md
- src/broyden.jl
- src/lbroyden.jl
- src/linesearch.jl
- test/basictests.jl
I left one mistake unfixed to see if it detects it.
> add spellcheck CI

- src/NonlinearSolve.jl
- src/broyden.jl
- src/default.jl
- src/jacobian.jl
- src/klement.jl
- src/trace.jl
- src/trustRegion.jl
- src/utils.jl
- test/23_test_problems.jl
- test/basictests.jl
- test/matrix_resizing.jl
See https://github.com/JuliaNLSolvers/NLsolve.jl/pull/287
Needs #297 to go in first
Fixes https://github.com/SciML/NonlinearSolve.jl/issues/260
1. Broyden and Klement can (re-)start with the true (inv-)jacobian if asked for
2. For Broyden, it improves robustness but makes Klement even more unstable for ill-conditioned problems
3. Klement with identity initialization makes the Jacobian always diagonal; the updated solver exploits this and is significantly faster
4. Klement for non-diagonal jacobians resets the jacobian if the jacobian is "too" ill-conditioned; this improves the stability somewhat
5. Bad Broyden Update Rule
6. Klement with true jacobian diagonal initialization
7. Initial Scaling factor to improve stability
> Improvements for Broyden and Klement

- .github/workflows/CI.yml
- test/23_test_problems.jl
- test/runtests.jl
Once https://github.com/SciML/DiffEqBase.jl/pull/972 this can be merged
> Disable protective check by default

- Project.toml
- docs/src/basics/NonlinearSolution.md
- ext/NonlinearSolveMINPACKExt.jl
- ext/NonlinearSolveNLsolveExt.jl
- src/levenberg.jl
- src/utils.jl
- test/23_test_problems.jl
> Minor Fixes

- docs/src/api/nonlinearsolve.md
- docs/src/solvers/NonlinearLeastSquaresSolvers.md
- src/jacobian.jl
- src/trace.jl
- src/trustRegion.jl
- test/nonlinear_least_squares.jl
Lol, it was a 1 line change.
The Yuan scheme had an inconsistency, but it has been fixed.
Fixes #252
> Trust Region Methods for Nonlinear Least Squares Problem

- Project.toml
- src/default.jl
- src/utils.jl
- test/polyalgs.jl
For line searches and trust region we can't support complex numbers correctly now. I am dropping them from the default right now.
> Handle complex numbers correctly by default

- Project.toml
- ext/NonlinearSolveMINPACKExt.jl
- ext/NonlinearSolveNLsolveExt.jl
- src/ad.jl
- src/jacobian.jl
- src/utils.jl
- test/basictests.jl
- test/forward_ad.jl
- test/runtests.jl
> ForwardDiff Proper Support

- Project.toml
- src/internal/helpers.jl
- src/internal/linear_solve.jl
- src/utils.jl
- test/core/rootfind.jl
For very simple problems with a diagonal Jacobian this is much faster.
Testing on the quadratic problem
```julia
julia> @benchmark solve(prob, NLsolveJL())
BenchmarkTools.Trial: 10000 samples with 5 evaluations.
Range (min … max):  6.047 μs …  2.675 ms  ┊ GC (min … max):  0.00% … 98.90%
Time  (median):     7.052 μs              ┊ GC (median):     0.00%
Time  (mean ± σ):   9.251 μs ± 50.774 μs  ┊ GC (mean ± σ):  10.88% ±  1.98%
▁█▂                                                       
▁▂███▆▃▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▃▃▃▄▄▄▃▄▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁ ▂
6.05 μs        Histogram: frequency by time        12.6 μs <
Memory estimate: 8.20 KiB, allocs estimate: 107.
julia> @benchmark solve(prob, NewtonRaphson(; linsolve = \, autodiff = AutoForwardDiff(; chunksize = 2)))
BenchmarkTools.Trial: 10000 …
```
> Allow linsolve to be \

- Project.toml
- src/internal/linear_solve.jl
~Strangely I can't locate the failing tests locally.~
> Fix DAE Test Failures in OrdinaryDiffEq

- src/algorithms/trust_region.jl
- test/misc/polyalgs.jl
fixes https://github.com/SciML/NonlinearSolve.jl/issues/360
> fix `autodiff=AutoFiniteDiff()` for `TrustRegion`

- .pre-commit-config.yaml
With 1.10 the overhead is very small to run it per-commit.
> Add precommit for formatting

- .github/workflows/Documentation.yml
- .github/workflows/Downstream.yml
Explicitly specify the codecov token to be used (i.e., `CODECOV_TOKEN`), given that the latest v4 release of the codecov action requires it to be able to generate coverage reports. Additionally, fail CI if coverage reporting fails, since coverage is an important enough metric for us to ensure that it's tracked consistently.
> ci: explicitly specify token for codecov

- Project.toml
- src/internal/linear_solve.jl
- test/misc/polyalg_tests.jl
> Fix static arrays

- Project.toml
> Enzyme breakage bump

- Project.toml
- ext/NonlinearSolveLeastSquaresOptimExt.jl
- ext/NonlinearSolveNLSolversExt.jl
- src/NonlinearSolve.jl
- src/abstract_types.jl
- src/core/noinit.jl
- test/misc/noinit_caching_tests.jl
- test/misc/qa_tests.jl
- test/wrappers/rootfind_tests.jl
This is needed because we want to write generic code with `init` and `solve!` without having to query every solver to check if it supports caching.
> Add caching for solvers without init

- Project.toml
- src/NonlinearSolve.jl
- src/algorithms/klement.jl
- src/algorithms/lbroyden.jl
- src/core/approximate_jacobian.jl
- src/default.jl
- src/globalization/line_search.jl
- src/internal/jacobian.jl
- src/utils.jl
- test/core/23_test_problems_tests.jl
- test/core/forward_ad_tests.jl
- test/core/nlls_tests.jl
- test/core/rootfind_tests.jl
- test/misc/matrix_resizing_tests.jl
- test/misc/polyalg_tests.jl
> Misc. Improvements

- Project.toml
- src/NonlinearSolve.jl
- src/default.jl
- src/utils.jl
- test/misc/aliasing_tests.jl
> Handle polyalgorithm aliasing correctly

- Project.toml
- src/utils.jl
Last piece of removing all forms of dynamic dispatches from MIRK methods
> Make `__findmin` type stable

- ext/NonlinearSolveNLSolversExt.jl
- src/internal/helpers.jl
- src/internal/operators.jl
See https://github.com/JuliaDiff/SparseDiffTools.jl/pull/290 for the corresponding one
> Don't use custom tags

- src/NonlinearSolve.jl
I'm not 100% sure this is working as intended (because these precompiles are over-specialized), but it does bring the precompile time down from ~150 seconds to 50 seconds on 4 cores.
> run precompile workload in parallel

- src/NonlinearSolve.jl
Remove Float32 method and the Vector out of place methods since these are less likely to be useful to users. This brings down precompilation time by ~2x. I think this is good to do before https://github.com/SciML/NonlinearSolve.jl/pull/418 since I'm more sure that it's a good idea.
> Simplify precompilation

- Project.toml
- docs/src/basics/nonlinear_solution.md
- src/NonlinearSolve.jl
- src/abstract_types.jl
- src/core/approximate_jacobian.jl
- src/core/generalized_first_order.jl
- src/core/generic.jl
- src/core/spectral_methods.jl
- src/default.jl
- src/descent/damped_newton.jl
- src/descent/newton.jl
- src/descent/steepest.jl
- src/globalization/line_search.jl
- src/globalization/trust_region.jl
- src/internal/approximate_initialization.jl
- src/internal/helpers.jl
- src/internal/jacobian.jl
- src/internal/linear_solve.jl
- src/internal/operators.jl
- src/internal/tracing.jl
- src/utils.jl
Fixes #410
Oops lost my local changes it seems...
Merge after https://github.com/SciML/NonlinearSolve.jl/pull/435
> Consolidate Stats Handling

- test/misc/ensemble_tests.jl
At some point, they just started working!
Fixes #365
> Add tests for Ensemble Problems

- src/NonlinearSolve.jl
- src/abstract_types.jl
- test/downstream/mtk_cache_indexing_tests.jl
> feat: support `setindex!` for nonlinear integrators

- src/globalization/line_search.jl
- test/core/rootfind_tests.jl
Added forward mode support to line searches. We prefer forward AD for better performance, however, reverse AD is also supported if user explicitly requests it.
1. If jvp is available, we use forward AD;
2. If reverse type is requested, we use reverse AD;
3. Otherwise, we use forward AD.
> Add forward mode to line search

- src/NonlinearSolve.jl
`@recompile_invalidations` should only be used in very specific scenarios, and this is not one of those scenarios. Also, there are big changes being done with https://github.com/SciML/CommonWorldInvalidations.jl. With that, we only need to `@recompile_invalidations` on a few entry points. In particular, Static.jl, Symbolics.jl, and preferably ForwardDiff.jl and StaticArrays.jl would adopt it too. But this means that in order to handle all of this effectively, in SciML we only need to apply it on Static.jl, Symbolics.jl, and SciMLBase.jl and the whole ecosystem should be fine.
In any case, this library doesn't need it. It shouldn't make a tangible difference in compile times, while it increases precompile times by a lot.
> Remove recompile_invalidations

- src/NonlinearSolve.jl
- src/internal/linear_solve.jl
- src/utils.jl
previously the preconditioner being set was a very complicated `IdentityOperator`. Using a regular `IdentityOperator` means that solvers that don't support one of the preconditioners won't throw warnings since they mostly know that `IdentityOperator`s aren't real.
> simplify `__wrapprecs`

- Project.toml
- docs/src/basics/sparsity_detection.md
- src/NonlinearSolve.jl
- src/internal/jacobian.jl
Seems to work beautifully. Haven't benchmarked yet, but the important part here is to ensure structure is preserved, since the main cost in these workloads is that Linear solving will be bottlnecked if a banded matrix is converted into a sparse matrix.
> feat: use DI for structured Jacobians

- src/internal/jacobian.jl
This should fix #469 for the example you gave.
> Use DI preparation result when initializing Jacobian

- docs/src/native/solvers.md
- docs/src/release_notes.md
- docs/src/tutorials/large_systems.md
- lib/NonlinearSolveBase/ext/NonlinearSolveBaseLinearSolveExt.jl
- lib/NonlinearSolveBase/src/descent/damped_newton.jl
- lib/NonlinearSolveBase/src/descent/dogleg.jl
- lib/NonlinearSolveBase/src/descent/newton.jl
- lib/NonlinearSolveBase/src/descent/steepest.jl
- lib/NonlinearSolveBase/src/jacobian.jl
- lib/NonlinearSolveBase/src/linear_solve.jl
- lib/NonlinearSolveFirstOrder/src/gauss_newton.jl
- lib/NonlinearSolveFirstOrder/src/levenberg_marquardt.jl
- lib/NonlinearSolveFirstOrder/src/pseudo_transient.jl
- lib/NonlinearSolveFirstOrder/src/raphson.jl
- lib/NonlinearSolveFirstOrder/src/trust_region.jl
- lib/NonlinearSolveFirstOrder/test/rootfind_tests.jl
- lib/NonlinearSolveQuasiNewton/src/klement.jl
- src/polyalg.jl
Updating https://github.com/SciML/NonlinearSolve.jl/pull/462 with the split.
> refactor!: move preconditioners inside linear solvers

- src/forward_diff.jl
- test/forward_ad_tests.jl
fixes https://github.com/SciML/NonlinearSolve.jl/issues/391
> fix: reinit! on forwarddiff cache

- lib/NonlinearSolveBase/src/solve.jl
- test/forward_ad_tests.jl
Fixes https://github.com/SciML/NonlinearSolve.jl/issues/497 . Noticed downstream
```
Candidates:
kwcall(::NamedTuple, ::typeof(SciMLBase.__solve), prob::SciMLBase.AbstractNonlinearProblem, alg::NonlinearSolveBase.NonlinearSolvePolyAlgorithm{Val{N}}, args...) where N
@ NonlinearSolveBase ~/.julia/packages/NonlinearSolveBase/54f3T/src/solve.jl:106
kwcall(::NamedTuple, ::typeof(SciMLBase.__solve), prob::Union{SciMLBase.NonlinearLeastSquaresProblem{<:Union{Number, var"#s15"} where var"#s15"<:AbstractArray, iip, <:Union{var"#s14", var"#s13"} where {var"#s14"<:ForwardDiff.Dual{T, V, P}, var"#s13"<:(AbstractArray{<:ForwardDiff.Dual{T, V, P}})}} where {iip, T, V, P}, SciMLBase.NonlinearProblem{<:Union{Number, var"#s15"} where var"#s15"<:AbstractArray, iip, <:Union{var"#s14", var"#s13"} where …
```
> Fix ambiguity in `__solve` with polyalgorithm due to dispatch on `Va`

- Project.toml
> Fix incorrect Base version

- docs/src/native/solvers.md
Fix a typo in the documentation
> docs: Fix typo

- lib/SimpleNonlinearSolve/src/SimpleNonlinearSolve.jl
- lib/SimpleNonlinearSolve/src/halley.jl
- lib/SimpleNonlinearSolve/src/raphson.jl
- lib/SimpleNonlinearSolve/src/utils.jl
- lib/SimpleNonlinearSolve/test/core/rootfind_tests.jl
This fixes an issue where we were returning a solution with a different `alg.autodiff` or `prob` if we had an `InitialFailure` vs a successful solve. This removes the allocations we were seeing in https://docs.sciml.ai/NonlinearSolve/stable/tutorials/code_optimization/#Further-Optimizations-for-Small-Nonlinear-Solves-with-Static-Arrays-and-SimpleNonlinearSolve.
Also fixes https://github.com/SciML/NonlinearSolve.jl/pull/536
> fix type stability of SimpleNonlinearSolve

- .github/workflows/CompatHelper.yml
Without checking out the repository, trying `readdir("lib")` will throw an error. Checking out the repository first fixes the presently broken CompatHelper action.
> ci(CompatHelper): checkout the repository

- docs/src/basics/diagnostics_api.md
- docs/src/basics/faq.md
- docs/src/tutorials/iterator_interface.md
- lib/NonlinearSolveBase/src/NonlinearSolveBase.jl
- lib/NonlinearSolveBase/src/jacobian.jl
- lib/NonlinearSolveBase/src/linear_solve.jl
- lib/NonlinearSolveBase/src/utils.jl
- lib/SimpleNonlinearSolve/src/utils.jl
- test/qa_tests.jl
Instead of only focusing on `similar` BigFloat throw `#undef` cases, we should use a more generic `similar` to cover more `#undef` cases.
> More generic safe similar

- Project.toml
- lib/NonlinearSolveFirstOrder/Project.toml
- lib/NonlinearSolveQuasiNewton/Project.toml
- lib/SciMLJacobianOperators/Project.toml
This is needed to support ForwardDiff@1.0. Testing separately to see how CI looks.
> support Zygote@0.7

- docs/src/native/bracketingnonlinearsolve.md
- docs/src/solvers/bracketing_solvers.md
- lib/BracketingNonlinearSolve/src/muller.jl
I implemented Muller's method into `BracketingNonlinearSolve.jl`, which was merged in #568. This pull request adds some more information to the docstring of `Muller` and updates the relevant documentation ([this](https://docs.sciml.ai/NonlinearSolve/stable/solvers/bracketing_solvers/) and [this page)](https://docs.sciml.ai/NonlinearSolve/stable/native/bracketingnonlinearsolve/).
In the process, I noticed that the former page had some out-of-date information; mentioning `SimpleNonlinearSolve.jl` when the listed methods are all now in `BracketingNonlinearSolve.jl`. I corrected this.
> Add documentation for Muller's method

- src/poly_algs.jl
This method is unlikely to be much better than normal Broyden or Klement and requires a pseudoinverse which is really bad for sparse jacobians. As such, this PR removes it when we aren't preferring the Simple algs
> remove true_jacobian Broyden from default alg

- src/poly_algs.jl
One of the properties the default polyalg wants is not just robustness to the mathematical problem but also robustness to implementation. Certain issues like https://github.com/EnzymeAD/Enzyme.jl/issues/2360#issuecomment-2823335480 have highlighted recently that Backtracking linesearch has a vjp, and then in the scenario that `using Enzyme` is done globally somewhere in the system, the autodiff chooser will prefer Enzyme. That's not necessarily a bad thing, but this leads to odd failures / fixes like https://github.com/SciML/OrdinaryDiffEq.jl/pull/2683 where a seemingly random change to test order fixes things. A fairly common example of how a user can trigger this is that if they do `using Enzyme`, then the forward pass of the default nonlinear solver will now have the Backtracking line …
> Simplify requirements from default polyalg

- docs/pages.jl
- docs/src/tutorials/nonlinear_solve_gpus.md
Fixes https://github.com/SciML/NonlinearSolve.jl/issues/405#issuecomment-2828189004
> Add a GPU tutorial

- docs/src/native/bracketingnonlinearsolve.md
- docs/src/solvers/bracketing_solvers.md
I noticed that the `Alefeld` method is currently missing on this [page](https://docs.sciml.ai/NonlinearSolve/stable/solvers/bracketing_solvers/) of the documentation. I also took the opportunity to alphabetise the lists.
> Add Alefeld method to documentation page

- test/cuda_tests.jl
This is a small fix. I've added a (second) `CUDA.functional()` if statement to the CUDA tests, so the test passes on machines that don't have an NVIDIA GPU installed or CUDA drivers.
> Fix test error for non-CUDA machines

- lib/SimpleNonlinearSolve/src/trust_region.jl
Fixes https://github.com/SciML/NonlinearSolve.jl/issues/596
> early exit in SimpleTrustRegion

- lib/NonlinearSolveBase/src/solve.jl
Only exit if less than tolerance
> Continue on with the polyalg if a stalledsuccess

- lib/NonlinearSolveHomotopyContinuation/src/jacobian_handling.jl
```julia
/home/runner/work/NonlinearSolve.jl/NonlinearSolve.jl/lib/NonlinearSolveHomotopyContinuation/test/single_root.jl:151
Got exception outside of a @test
PreparationMismatchError (inconsistent types between preparation and execution):
- f!: ✅
- y: ✅
- backend: ✅
- x: ❌
- prep: Vector{Float64}
- exec: Base.ReinterpretArray{Float64, 1, ComplexF64, Vector{ComplexF64}, false}
- contexts: ✅
If you are confident that this check is superfluous, you can disable it by running preparation with the keyword argument `strict=Val(false)` inside DifferentiationInterface.
```
Reinterpret seems to bug it so it's easiest to just remove it.
> Set strict=false for DI in HomotopyContinuation

- lib/NonlinearSolveBase/src/jacobian.jl
- lib/SciMLJacobianOperators/src/SciMLJacobianOperators.jl
- lib/SimpleNonlinearSolve/src/utils.jl
The issue is that DI strictness does not allow views, even though most of the AD engines are fine with views.
> Turn off DI strictness

- lib/NonlinearSolveBase/src/common_defaults.jl
This is definitely a bug somewhere, but without this `@report_opt` or `@report_trim` reports errors here.
> Hardcode `get_tolerance` for `Float64` for trimming

- lib/SciMLJacobianOperators/src/SciMLJacobianOperators.jl
Attempt to fix https://github.com/SciML/NonlinearSolve.jl/issues/690
> Add copy methods for Jacobian Operators

- lib/SciMLJacobianOperators/src/SciMLJacobianOperators.jl
This ends up trying to copy a Tuple of ints, which does not work.
> Copying SciMLJacobianOperators should not copy the size 

- lib/SciMLJacobianOperators/src/SciMLJacobianOperators.jl
This should make sure that `copy` uses the correct constructors for the JacobianOperators. This passes tests locally.
> Use correct constructors for JacobianOperators in `copy`

- lib/NonlinearSolveBase/src/termination_conditions.jl
- lib/NonlinearSolveBase/test/runtests.jl
Fixed an issue where calling `reinit!` with `AbsTerminationMode` would throw:
```julia
MethodError: no method matching ndims(::Type{Nothing})
undefined
```
The `NonlinearTerminationModeCache` for `AbsTerminationMode` initializes `u` as `nothing`, but `reinit!` attempted to broadcast into it. The fix ensures we only update `cache.u` when it's not `nothing`.
Added guard clause to skip updating `cache.u` when it's `nothing`:
```julia
if cache.u !== nothing
#...existing logic...
end
```
Added regression test that creates a termination cache with `u_unaliased = nothing` and verifies `reinit!` no longer throws:
```julia
@testset "reinit! with AbsTerminationMode" begin
mode = AbsTerminationMode()
cache = NonlinearTerminationModeCache(
nothing, ReturnCode.Default, 1e-8, 1e-8, Inf, mode,
nothing, …
```
> Fix: reinit! error when using AbsTerminationMode
